### ISSUE TITLE
Remove Jade Edict 

### ISSUE THREAD

**Issue by programming-wolf** [Emerald-Legacy/emeralddb#54]
We do not need the Jade Edict format anymore, Emerald Legacy and Imperial are the two modes that are played, no one plays Jade anymore.

**Comment by xWorkerBeex** [comment]
The format still exists, but with the changes I just pushed you aren't able to build new decks with it or filter for banned cards, etc. 
This prevents us from having to write a migration where we remove the value "jade-edict" from multiple entities like Cards or Decks
